title   Arch Linux (rescue system)
linux   /EFI/archiso/boot/x86_64/vmlinuz-linux.signed
initrd  /intel-ucode.img
initrd  /EFI/archiso/boot/x86_64/initramfs-linux.img
options archisobasedir=/EFI/archiso archisosearchfilename=/EFI/archiso/boot/x86_64/vmlinuz-linux
