title   Arch Linux
linux   /arch/vmlinuz-linux.signed
initrd  /intel-ucode.img
initrd  /arch/initramfs-linux.img
options root=UUID=ceeb160c-a95f-4563-96fb-22819c48c4ca rw rootflags=subvol=@ nvidia_drm.modeset=1
